#!/usr/bin/env bash
# ============================================================================
# Kozakova_Pomsta — clean re-init
# Run with GIT BASH (comes with Git for Windows), from the project root
# (the folder that contains the .git folder), on the PC where the project
# opens correctly in Unity with no missing/corrupt assets.
#
#   Right-click the project folder -> "Git Bash Here" -> bash reinit_repo.sh
# ============================================================================
set -e

if [ ! -d ".git" ]; then
  echo "ERROR: run this from the ROOT of the project (where .git lives)."
  exit 1
fi

echo "############################################################"
echo "STEP 0: Backup the old (broken) git history, just in case"
echo "############################################################"
if [ -d ".git_broken_backup" ]; then
  echo "A backup already exists at .git_broken_backup - remove/rename it first."
  exit 1
fi
mv .git .git_broken_backup
echo "Old history moved to .git_broken_backup (not deleted, just out of the way)."

echo ""
echo "############################################################"
echo "STEP 1: Write a clean .gitignore for Unity"
echo "############################################################"
cat > .gitignore << 'EOF'
# Unity generated folders
/Library/
/Temp/
/Obj/
/Build/
/Builds/
/Logs/
/UserSettings/
/MemoryCaptures/
/Recordings/

# Visual Studio / Rider / VS Code
.vs/
.vscode/
.idea/
*.csproj
*.sln
*.user
*.userprefs
ExportedObj/
.consulo/
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Autogenerated caches that don't need to be in source control
Assets/Unity.VisualScripting.Generated/

# Blender autosave/backup files (not needed, Blender regenerates them)
*.blend1
*.blend2

# OS junk
.DS_Store
Thumbs.db
EOF
echo "Wrote .gitignore"

echo ""
echo "############################################################"
echo "STEP 2: Write .gitattributes WITHOUT Git LFS"
echo "############################################################"
echo "(Your largest tracked file is ~40MB, well under GitHub's 100MB hard"
echo " limit, so plain Git is simpler and avoids this entire class of bug."
echo " If the repo grows a lot in the future, LFS can be reintroduced later"
echo " -- carefully, and with 'git lfs push --all' actually run before"
echo " anyone else clones.)"
cat > .gitattributes << 'EOF'
# Unity YAML / text assets - normalize line endings, no LFS
*.cs      text diff=csharp eol=lf
*.shader  text eol=lf
*.cginc   text eol=lf
*.hlsl    text eol=lf
*.compute text eol=lf
*.asset   text eol=lf
*.anim    text eol=lf
*.controller text eol=lf
*.mat     text eol=lf
*.prefab  text eol=lf
*.unity   text eol=lf
*.meta    text eol=lf
*.asmdef  text eol=lf

# Binary assets - do not touch, no LFS
*.png  binary
*.jpg  binary
*.jpeg binary
*.tif  binary
*.tga  binary
*.psd  binary
*.exr  binary
*.fbx  binary
*.blend binary
*.wav  binary
*.mp3  binary
*.ogg  binary
EOF
echo "Wrote .gitattributes"

echo ""
echo "############################################################"
echo "STEP 3: Make sure nothing routes through a leftover LFS filter"
echo "############################################################"
git lfs uninstall --local 2>/dev/null || true
git config --unset-all filter.lfs.clean 2>/dev/null || true
git config --unset-all filter.lfs.smudge 2>/dev/null || true
git config --unset-all filter.lfs.process 2>/dev/null || true

echo ""
echo "############################################################"
echo "STEP 4: Fresh init and single clean commit from the real files"
echo "         currently on disk (the ones that work in Unity)"
echo "############################################################"
git init -b main
git add -A
git commit -m "Clean re-init: replace broken LFS history with working project files"

echo ""
echo "############################################################"
echo "DONE. Review, then push."
echo "############################################################"
echo "Next steps:"
echo "  git remote add origin https://github.com/LowLightCZ1/Kozakova_Pomsta.git"
echo "  git push --force origin main"
echo ""
echo "!!! IMPORTANT: after this push, your collaborator must DELETE their"
echo "!!! entire old local clone folder and clone fresh - do NOT git pull"
echo "!!! into the old broken clone, the histories no longer share ancestry."
